micronaut:
  application:
    name: mnMonogMultitenant
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}

grails:
  mongodb:
    host: "localhost"
    port: 27017
    username: admin
    password: madmin
    databaseName: "test"
    multiTenancy:
      mode: DISCRIMINATOR
      tenantResolverClass: org.grails.datastore.mapping.multitenancy.web.HttpHeaderTenantResolver